version: '3.9'
services:
  dbPostgres:
    image: postgres:14.15-alpine3.20
    shm_size: 128mb
    environment:
      POSTGRES_USER: Alex
      POSTGRES_PASSWORD: ahfiuqy4ouhblirughsliujkglstithglskrlhjgl
      POSTGRES_DB: JobPro
    ports:
      - "5432:5432"
    volumes:
      - dbPostgrest_data:/var/lib/postgresql/data

  dbRedis:
    image: redis:7.4.1-alpine3.20
    ports:
      - "6379:6379"
    volumes:
      - dbRedis_data:/data

volumes:
  dbPostgrest_data:
  dbRedis_data:
